INSERT INTO T_OSI_REFERENCE ( SID, USAGE, CODE, DESCRIPTION, SEQ, ACTIVE, CREATE_BY, CREATE_ON, MODIFY_BY, MODIFY_ON, COMMENTS ) VALUES ( 
'33318PK3', 'DOCREV_DOCTYPE', 'SADR', 'Surveillance Activity Data Review', 17.5, 'Y', 'timothy.ward',  TO_Date( '05/22/2012 07:29:43 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'timothy.ward',  TO_Date( '05/22/2012 07:29:43 AM', 'MM/DD/YYYY HH:MI:SS AM'), NULL); 
COMMIT;
