------------------------------------------------------------
--- 3681-Split DOD Service Affiliation into DoD Agencies ---
------------------------------------------------------------
ALTER TABLE T_DIBRS_REFERENCE ADD REPORT_AS VARCHAR2(50);

UPDATE T_DIBRS_REFERENCE SET REPORT_AS=CODE;
COMMIT;

update t_dibrs_reference set description='Dept of Defense (Other)',seq=4.17 where usage='SERVICE_TYPE' and CODE='D' and description='Dept of Defense';
commit;

INSERT INTO T_DIBRS_REFERENCE ( SID, USAGE, CODE, DESCRIPTION, SEQ, ACTIVE, CREATE_BY, CREATE_ON, MODIFY_BY, MODIFY_ON, COMMENTS, REPORT_AS ) VALUES ( '3331678K', 'SERVICE_TYPE', 'DARPA', 'DARPA', 4.01, 'Y', 'timothy.ward',  TO_Date( '05/18/2011 12:07:16 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'timothy.ward',  TO_Date( '05/18/2011 12:14:31 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'Reference table for Military Service types supplied by DIBRS.', 'D'); 
INSERT INTO T_DIBRS_REFERENCE ( SID, USAGE, CODE, DESCRIPTION, SEQ, ACTIVE, CREATE_BY, CREATE_ON, MODIFY_BY, MODIFY_ON, COMMENTS, REPORT_AS ) VALUES ( '3331678L', 'SERVICE_TYPE', 'DCM', 'DCM', 4.03, 'Y', 'timothy.ward',  TO_Date( '05/18/2011 12:07:50 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'timothy.ward',  TO_Date( '05/18/2011 12:14:38 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'Reference table for Military Service types supplied by DIBRS.', 'D'); 
INSERT INTO T_DIBRS_REFERENCE ( SID, USAGE, CODE, DESCRIPTION, SEQ, ACTIVE, CREATE_BY, CREATE_ON, MODIFY_BY, MODIFY_ON, COMMENTS, REPORT_AS ) VALUES ( '3331678M', 'SERVICE_TYPE', 'DCAA', 'DCAA', 4.02, 'Y', 'timothy.ward',  TO_Date( '05/18/2011 12:08:06 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'timothy.ward',  TO_Date( '05/18/2011 12:14:34 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'Reference table for Military Service types supplied by DIBRS.', 'D'); 
INSERT INTO T_DIBRS_REFERENCE ( SID, USAGE, CODE, DESCRIPTION, SEQ, ACTIVE, CREATE_BY, CREATE_ON, MODIFY_BY, MODIFY_ON, COMMENTS, REPORT_AS ) VALUES ( '3331678N', 'SERVICE_TYPE', 'DCMA', 'DCMA', 4.04, 'Y', 'timothy.ward',  TO_Date( '05/18/2011 12:08:24 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'timothy.ward',  TO_Date( '05/18/2011 12:14:41 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'Reference table for Military Service types supplied by DIBRS.', 'D'); 
INSERT INTO T_DIBRS_REFERENCE ( SID, USAGE, CODE, DESCRIPTION, SEQ, ACTIVE, CREATE_BY, CREATE_ON, MODIFY_BY, MODIFY_ON, COMMENTS, REPORT_AS ) VALUES ( '3331678O', 'SERVICE_TYPE', 'DFAS', 'DFAS', 4.05, 'Y', 'timothy.ward',  TO_Date( '05/18/2011 12:08:43 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'timothy.ward',  TO_Date( '05/18/2011 12:14:44 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'Reference table for Military Service types supplied by DIBRS.', 'D'); 
INSERT INTO T_DIBRS_REFERENCE ( SID, USAGE, CODE, DESCRIPTION, SEQ, ACTIVE, CREATE_BY, CREATE_ON, MODIFY_BY, MODIFY_ON, COMMENTS, REPORT_AS ) VALUES ( '3331678P', 'SERVICE_TYPE', 'DISA', 'DISA', 4.07, 'Y', 'timothy.ward',  TO_Date( '05/18/2011 12:08:59 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'timothy.ward',  TO_Date( '05/18/2011 12:14:50 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'Reference table for Military Service types supplied by DIBRS.', 'D'); 
INSERT INTO T_DIBRS_REFERENCE ( SID, USAGE, CODE, DESCRIPTION, SEQ, ACTIVE, CREATE_BY, CREATE_ON, MODIFY_BY, MODIFY_ON, COMMENTS, REPORT_AS ) VALUES ( '3331678Q', 'SERVICE_TYPE', 'DIA', 'DIA', 4.06, 'Y', 'timothy.ward',  TO_Date( '05/18/2011 12:09:13 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'timothy.ward',  TO_Date( '05/18/2011 12:14:47 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'Reference table for Military Service types supplied by DIBRS.', 'D'); 
INSERT INTO T_DIBRS_REFERENCE ( SID, USAGE, CODE, DESCRIPTION, SEQ, ACTIVE, CREATE_BY, CREATE_ON, MODIFY_BY, MODIFY_ON, COMMENTS, REPORT_AS ) VALUES ( '3331678R', 'SERVICE_TYPE', 'DLSA', 'DLSA', 4.09, 'Y', 'timothy.ward',  TO_Date( '05/18/2011 12:09:30 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'timothy.ward',  TO_Date( '05/18/2011 12:14:57 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'Reference table for Military Service types supplied by DIBRS.', 'D'); 
INSERT INTO T_DIBRS_REFERENCE ( SID, USAGE, CODE, DESCRIPTION, SEQ, ACTIVE, CREATE_BY, CREATE_ON, MODIFY_BY, MODIFY_ON, COMMENTS, REPORT_AS ) VALUES ( '3331678S', 'SERVICE_TYPE', 'DLA', 'DLA', 4.08, 'Y', 'timothy.ward',  TO_Date( '05/18/2011 12:09:45 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'timothy.ward',  TO_Date( '05/18/2011 12:14:54 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'Reference table for Military Service types supplied by DIBRS.', 'D'); 
INSERT INTO T_DIBRS_REFERENCE ( SID, USAGE, CODE, DESCRIPTION, SEQ, ACTIVE, CREATE_BY, CREATE_ON, MODIFY_BY, MODIFY_ON, COMMENTS, REPORT_AS ) VALUES ( '3331678T', 'SERVICE_TYPE', 'DSCA', 'DSCA', 4.1, 'Y', 'timothy.ward',  TO_Date( '05/18/2011 12:10:01 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'timothy.ward',  TO_Date( '05/18/2011 12:14:05 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'Reference table for Military Service types supplied by DIBRS.', 'D'); 
INSERT INTO T_DIBRS_REFERENCE ( SID, USAGE, CODE, DESCRIPTION, SEQ, ACTIVE, CREATE_BY, CREATE_ON, MODIFY_BY, MODIFY_ON, COMMENTS, REPORT_AS ) VALUES ( '3331678U', 'SERVICE_TYPE', 'DSS', 'DSS', 4.11, 'Y', 'timothy.ward',  TO_Date( '05/18/2011 12:10:15 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'timothy.ward',  TO_Date( '05/18/2011 12:17:18 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'Reference table for Military Service types supplied by DIBRS.', 'D'); 
INSERT INTO T_DIBRS_REFERENCE ( SID, USAGE, CODE, DESCRIPTION, SEQ, ACTIVE, CREATE_BY, CREATE_ON, MODIFY_BY, MODIFY_ON, COMMENTS, REPORT_AS ) VALUES ( '3331678V', 'SERVICE_TYPE', 'DTRA', 'DTRA', 4.12, 'Y', 'timothy.ward',  TO_Date( '05/18/2011 12:10:32 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'timothy.ward',  TO_Date( '05/18/2011 12:17:22 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'Reference table for Military Service types supplied by DIBRS.', 'D'); 
INSERT INTO T_DIBRS_REFERENCE ( SID, USAGE, CODE, DESCRIPTION, SEQ, ACTIVE, CREATE_BY, CREATE_ON, MODIFY_BY, MODIFY_ON, COMMENTS, REPORT_AS ) VALUES ( '3331678W', 'SERVICE_TYPE', 'MDA', 'MDA', 4.13, 'Y', 'timothy.ward',  TO_Date( '05/18/2011 12:10:51 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'timothy.ward',  TO_Date( '05/18/2011 12:17:26 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'Reference table for Military Service types supplied by DIBRS.', 'D'); 
INSERT INTO T_DIBRS_REFERENCE ( SID, USAGE, CODE, DESCRIPTION, SEQ, ACTIVE, CREATE_BY, CREATE_ON, MODIFY_BY, MODIFY_ON, COMMENTS, REPORT_AS ) VALUES ( '3331678X', 'SERVICE_TYPE', 'NIMA', 'NIMA', 4.14, 'Y', 'timothy.ward',  TO_Date( '05/18/2011 12:11:08 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'timothy.ward',  TO_Date( '05/18/2011 12:17:30 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'Reference table for Military Service types supplied by DIBRS.', 'D'); 
INSERT INTO T_DIBRS_REFERENCE ( SID, USAGE, CODE, DESCRIPTION, SEQ, ACTIVE, CREATE_BY, CREATE_ON, MODIFY_BY, MODIFY_ON, COMMENTS, REPORT_AS ) VALUES ( '3331678Y', 'SERVICE_TYPE', 'NSA/CCS', 'NSA/CCS', 4.15, 'Y', 'timothy.ward',  TO_Date( '05/18/2011 12:11:35 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'timothy.ward',  TO_Date( '05/18/2011 12:17:34 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'Reference table for Military Service types supplied by DIBRS.', 'D'); 
INSERT INTO T_DIBRS_REFERENCE ( SID, USAGE, CODE, DESCRIPTION, SEQ, ACTIVE, CREATE_BY, CREATE_ON, MODIFY_BY, MODIFY_ON, COMMENTS, REPORT_AS ) VALUES ( '3331678Z', 'SERVICE_TYPE', 'PPA', 'PPA', 4.16, 'Y', 'timothy.ward',  TO_Date( '05/18/2011 12:11:52 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'timothy.ward',  TO_Date( '05/18/2011 12:17:37 PM', 'MM/DD/YYYY HH:MI:SS AM'), 'Reference table for Military Service types supplied by DIBRS.', 'D'); 
COMMIT;