delete from T_OSI_CHECKLIST_ITEM_TYPE_MAP
WHERE STATUS_CHANGE_SID=(SELECT SID FROM T_OSI_STATUS_CHANGE WHERE CHECKLIST_BUTTON_LABEL='DOA - Determination Of Availability Checklist')
  AND CHECKLIST_ITEM_TYPE_SID=(SELECT SID FROM T_OSI_CHECKLIST_ITEM_TYPE WHERE TITLE='DLAB documents attached.');
COMMIT;   