--run on i2ms schema
GRANT SELECT ON T_ACTIVITY TO MIS;
GRANT SELECT ON V_FILE_LOOKUP_V2 TO MIS;
GRANT SELECT ON T_FILE_CONTENT TO MIS;
GRANT SELECT ON T_CR_USAGE TO MIS;
GRANT SELECT ON T_IR_SOURCE TO MIS;
COMMIT;