--run on webi2ms schema
CREATE SYNONYM REF_T_ACTIVITY FOR i2ms.T_ACTIVITY@LEGACY.DIMRO;
CREATE SYNONYM REF_V_FILE_LOOKUP_V2 for i2ms.V_FILE_LOOKUP_V2@LEGACY.DIMRO;
CREATE SYNONYM REF_T_FILE_CONTENT for i2ms.T_FILE_CONTENT@LEGACY.DIMRO;
CREATE SYNONYM REF_T_CR_USAGE for i2ms.T_CR_USAGE@LEGACY.DIMRO;
CREATE SYNONYM REF_T_IR_SOURCE for i2ms.T_IR_SOURCE@LEGACY.DIMRO;
commit;