--Add IMP_RELATIONS flag to T_OSI_MIGRATION

ALTER TABLE T_OSI_MIGRATION
 ADD (IMP_RELATIONS  VARCHAR2(1 BYTE));

--Initialize IMP_RELATIONS to 'N' for all Participant type rows
update T_OSI_MIGRATION set imp_relations = 'N' where type = 'PARTICIPANT';
COMMIT;

--Insert the checklist item type

SET DEFINE OFF;
Insert into T_OSI_CHECKLIST_ITEM_TYPE
   (SID, TITLE, DESCRIPTION, VERIFY_PROC)
 Values
   ('2220PZ9K', 'Legacy relationships must be imported.', 'Legacy I2MS must be searched for relationships to migrated Participants.', 'OSI_CHECKLIST.VERIFY_LEGACY_RELATIONSHIPS');
COMMIT;


--Insert the checklist/status mappings for FILE.INV.CASE statuses (that also require Confirmed Participants)
SET DEFINE OFF;
Insert into T_OSI_CHECKLIST_ITEM_TYPE_MAP
   (SID, STATUS_CHANGE_SID, CHECKLIST_ITEM_TYPE_SID, USER_EDITABLE, COMPLETION_REQUIRED)
 Values
   ('2220PZCS', '22200000GDD', '2220PZ9K', 0, 1);
Insert into T_OSI_CHECKLIST_ITEM_TYPE_MAP
   (SID, STATUS_CHANGE_SID, CHECKLIST_ITEM_TYPE_SID, USER_EDITABLE, COMPLETION_REQUIRED)
 Values
   ('2220PZCT', '22200000GD9', '2220PZ9K', 0, 1);
Insert into T_OSI_CHECKLIST_ITEM_TYPE_MAP
   (SID, STATUS_CHANGE_SID, CHECKLIST_ITEM_TYPE_SID, USER_EDITABLE, COMPLETION_REQUIRED)
 Values
   ('2220PZCU', '22200000GDC', '2220PZ9K', 0, 1);
Insert into T_OSI_CHECKLIST_ITEM_TYPE_MAP
   (SID, STATUS_CHANGE_SID, CHECKLIST_ITEM_TYPE_SID, USER_EDITABLE, COMPLETION_REQUIRED)
 Values
   ('2220PZCV', '22200000GD7', '2220PZ9K', 0, 1);
COMMIT;

--Insert the checklist/status mappings for Participant Confirmation
SET DEFINE OFF;
Insert into T_OSI_CHECKLIST_ITEM_TYPE_MAP
   (SID, STATUS_CHANGE_SID, CHECKLIST_ITEM_TYPE_SID, USER_EDITABLE, COMPLETION_REQUIRED)
 Values
   ('2220Q50G', '22200000HVY', '2220PZ9K', 0, 1);
Insert into T_OSI_CHECKLIST_ITEM_TYPE_MAP
   (SID, STATUS_CHANGE_SID, CHECKLIST_ITEM_TYPE_SID, USER_EDITABLE, COMPLETION_REQUIRED)
 Values
   ('2220Q50F', '22200000CQL', '2220PZ9K', 0, 1);
Insert into T_OSI_CHECKLIST_ITEM_TYPE_MAP
   (SID, STATUS_CHANGE_SID, CHECKLIST_ITEM_TYPE_SID, USER_EDITABLE, COMPLETION_REQUIRED)
 Values
   ('2220Q50H', '22200000HVZ', '2220PZ9K', 0, 1);
Insert into T_OSI_CHECKLIST_ITEM_TYPE_MAP
   (SID, STATUS_CHANGE_SID, CHECKLIST_ITEM_TYPE_SID, USER_EDITABLE, COMPLETION_REQUIRED)
 Values
   ('2220Q50I', '22200000HW0', '2220PZ9K', 0, 1);
COMMIT;
