--run on webi2ms schema
--CREATE SYNONYM REF_T_PERSON_TYPE FOR I2MS.T_PERSON_TYPE;
--CREATE SYNONYM REF_T_PERSON_NAME_TYPE FOR I2MS.T_PERSON_NAME_TYPE;

CREATE SYNONYM REF_T_PERSON_TYPE FOR i2ms.T_PERSON_TYPE@LEGACY.DIMRO;
CREATE SYNONYM REF_T_PERSON_NAME_TYPE FOR i2ms.T_PERSON_NAME_TYPE@LEGACY.DIMRO;
