INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV) SELECT R.SID,P.SID FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P,T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A WHERE R.CODE IN ('IGAGT','HQIG') AND T.CODE='FILE' AND T.SID=P.OBJ_TYPE AND A.CODE='ACCESS' AND A.SID=P.ACTION;
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV) SELECT R.SID,P.SID FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P,T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A WHERE R.CODE IN ('IGAGT','HQIG') AND T.CODE='FILE' AND T.SID=P.OBJ_TYPE AND A.CODE='OVERRIDE' AND A.SID=P.ACTION;
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV) SELECT R.SID,P.SID FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P,T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A WHERE R.CODE IN ('IGAGT','HQIG') AND T.CODE='ACT' AND T.SID=P.OBJ_TYPE AND A.CODE='OVERRIDE' AND A.SID=P.ACTION;
commit;




/****************************************************************** TESTING ONLY 
---SELECT R.SID FROM T_OSI_AUTH_ROLE R WHERE R.CODE IN ('IGAGT');
---SELECT P.SID FROM T_OSI_AUTH_PRIV P,T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A WHERE  T.CODE='ACT.POLY_EXAM' AND T.SID=P.OBJ_TYPE AND A.CODE='OVERRIDE' AND A.SID=P.ACTION;
---select * from t_osi_auth_action_type where code='OVERRIDE'
---DESC T_OSI_AUTH_PRIV
*******************************************************************/