----------------------------------------------------------------------------------------------------------------------
--- COMMANDER, RGNAPP, RGNCOMMAND, RGNSUPER, RGNVC, SQDCOMMAND, SUPER, RGNIMA, IMACC, IMASUPER ACT.AAPP Privileges ---
----------------------------------------------------------------------------------------------------------------------
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV) 
      SELECT R.SID,P.SID FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P,T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A 
            WHERE R.CODE IN ('COMMANDER','RGNAPP','RGNCOMMAND','RGNSUPER','RGNVC','SQDCOMMAND','SUPER','RGNIMA','IMACC','IMASUPER') AND T.CODE='ACT.AAPP' AND T.SID=P.OBJ_TYPE AND A.CODE='REOPEN' AND A.SID=P.ACTION;
COMMIT;

--------------------------------------
--- COMMANDER FILE.AAPP Privileges ---
--------------------------------------
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV) 
      SELECT R.SID,P.SID FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P,T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A 
            WHERE R.CODE IN ('COMMANDER') AND T.CODE='FILE.AAPP' AND T.SID=P.OBJ_TYPE AND A.CODE IN ('AAPP_CM','AAPP_CRE','AAPP_DPPI','AAPP_RA','AAPP_ROPN','AAPP_SARC','AAPP_UOWM','AAPP_XFR','ACCESS','ACCESS_UNT','CLOSE','CREATE') AND A.SID=P.ACTION;
COMMIT;

-------------------------------------------------------------------------------------------
--- RGNCOMMMAND, RGNSUPER, RGNVC, SQDCOMMAND, SUPER, RGNIMA, IMACC FILE.AAPP Privileges ---
-------------------------------------------------------------------------------------------
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV) 
      SELECT R.SID,P.SID FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P,T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A WHERE R.CODE IN ('RGNCOMMAND','RGNSUPER','RGNVC','SQDCOMMAND','SUPER','RGNIMA','IMACC') AND T.CODE='FILE.AAPP' AND T.SID=P.OBJ_TYPE AND A.CODE IN ('AAPP_CM','AAPP_CRE','AAPP_DPPI','AAPP_RA','AAPP_ROPN','AAPP_SARC','AAPP_UOWM','AAPP_XFR','ACCESS_UNT','CLOSE','CREATE') AND A.SID=P.ACTION;
COMMIT;

-----------------------------------
--- RGNAPP FILE.AAPP Privileges ---
-----------------------------------
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV) 
      SELECT R.SID,P.SID FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P,T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A WHERE R.CODE IN ('RGNAPP') AND T.CODE='FILE.AAPP' AND T.SID=P.OBJ_TYPE AND A.CODE IN ('AAPP_CM','AAPP_CRE','AAPP_DPPI','AAPP_ROPN','AAPP_SARC','AAPP_UOWM','AAPP_XFR','ACCESS_UNT','CLOSE','CREATE') AND A.SID=P.ACTION;
COMMIT;

-------------------------------------
--- IMASUPER FILE.AAPP Privileges ---
-------------------------------------
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV) 
      SELECT R.SID,P.SID FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P,T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A 
            WHERE R.CODE IN ('IMASUPER') AND T.CODE='FILE.AAPP' AND T.SID=P.OBJ_TYPE AND A.CODE IN ('AAPP_CM','AAPP_CRE','AAPP_DPPI','AAPP_RA','AAPP_ROPN','AAPP_SARC','AAPP_UOWM','AAPP_XFR','ACCESS','ACCESS_UNT','CLOSE','CREATE','OVERRIDE') AND A.SID=P.ACTION;
COMMIT;






--------------------------------------------------------
--- MISC ONES THAT WERE MISSING FILE.AAPP Privileges ---
--------------------------------------------------------
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV) 
      SELECT R.SID,P.SID FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P,T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A 
            WHERE R.CODE IN ('IMACC','RGNCOMMAND','RGNIMA','RGNSUPER','RGNVC','SQDCOMMAND','SUPER') AND T.CODE='FILE.AAPP' AND T.SID=P.OBJ_TYPE AND A.CODE IN ('ACCESS') AND A.SID=P.ACTION;
COMMIT;


INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV) 
      SELECT R.SID,P.SID FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P,T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A 
            WHERE R.CODE IN ('RGNAPP') AND T.CODE='FILE.AAPP' AND T.SID=P.OBJ_TYPE AND A.CODE IN ('AAPP_UL') AND A.SID=P.ACTION;
COMMIT;

