INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV) SELECT R.SID,P.SID FROM
T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P,T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A 
WHERE R.CODE IN ('BRANCH',/*'COMMANDER',*/'HQAPP','HQCCICFFE'/*,'HQCFUNDS','HQCOMMAND'*/,'HQFOR','HQHELP','HQIG'/*,'HQPMO','HQPOLY'*/,'HQTECH',/*'HQWATCH','IMACC',*/'IMASUPER',/*'RGNCFUNDS','RGNCOMMAND',*/'RGNDD',/*'RGNIMA','RGNSC','RGNSUPER','RGNVC','SQDCOMMAND',*/'SUPER') 
  AND T.CODE='PERSONNEL' AND T.SID=P.OBJ_TYPE AND A.CODE='PMM_MODPRV' AND A.SID=P.ACTION;

--SELECT R.SID FROM T_OSI_AUTH_ROLE R WHERE R.CODE IN ('BRANCH','COMMANDER','HQAPP','HQCCICFEE','HQCFUNDS','HQCOMMAND','HQFOR','HQHELP','HQIG','HQPMO','HQPOLY','HQTECH','HQWATCH','IMACC','IMASUPER','RGNCFUNDS','RGNCOMMAND','RGNDD','RGNIMA','RGNSC','RGNSUPER','RGNVC','SQDCOMMAND','SUPER')

--SELECT P.SID FROM T_OSI_AUTH_PRIV P,T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A WHERE  T.CODE='PERSONNEL' AND T.SID=P.OBJ_TYPE AND A.CODE='PMM_MODPRV' AND A.SID=P.ACTION;

---SELECT P.SID FROM T_OSI_AUTH_PRIV P,T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A WHERE  T.CODE='PERSONNEL' AND T.SID=P.OBJ_TYPE AND A.CODE='PMM_MODROL' AND A.SID=P.ACTION;
--SELECT CODE FROM T_OSI_AUTH_ROLE_PRIV P,T_OSI_AUTH_ROLE R WHERE PRIV='22200000OYW' AND P.ROLE=R.SID ORDER BY CODE

--select code from t_osi_auth_role_priv p,t_osi_auth_role r where priv='22200000OYV' and p.role=r.sid ORDER BY CODE;

COMMIT;