CREATE INDEX I_OSI_COMPINT_INTRU_IMP ON T_OSI_A_COMP_INTRUSION
(INTRUSION_IMPACT)
LOGGING
NOPARALLEL;

CREATE INDEX I_OSI_COMPINT_CONT_METH ON T_OSI_A_COMP_INTRUSION
(CONTACT_METHOD)
LOGGING
NOPARALLEL;

CREATE INDEX I_OSI_COMPINT_AFCERT_CAT ON T_OSI_A_COMP_INTRUSION
(AFCERT_CATEGORY)
LOGGING
NOPARALLEL;

ALTER TABLE T_OSI_A_COMP_INTRUSION ADD (
CONSTRAINT FK_OSI_COMPINT_INTRU_IMP
     FOREIGN KEY (INTRUSION_IMPACT)
     REFERENCES T_OSI_REFERENCE (SID),
CONSTRAINT FK_OSI_COMPINT_CONT_METH
     FOREIGN KEY (CONTACT_METHOD)
     REFERENCES T_OSI_REFERENCE (SID),
CONSTRAINT FK_OSI_COMPINT_AFCERT_CAT
     FOREIGN KEY (AFCERT_CATEGORY)
     REFERENCES T_OSI_REFERENCE (SID)
);