UPDATE T_OSI_STATUS_CHANGE SET AUTH_ACTION=(SELECT SID FROM T_OSI_AUTH_ACTION_TYPE T WHERE T.CODE='APPROVE') 
      WHERE TRANSITION='Reject Approval' AND OBJ_TYPE IN (SELECT SID FROM T_CORE_OBJ_TYPE WHERE CODE='FILE.INV');
COMMIT;      