INSERT INTO T_OSI_AUTH_PRIV (OBJ_TYPE,ACTION) SELECT T.SID,A.SID FROM T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A WHERE T.CODE='ACT.COORDINATION.AUTOPSY' AND A.CODE='CREATE';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV) SELECT R.SID,P.SID FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P,T_CORE_OBJ_TYPE T WHERE R.CODE='AGTPERS' AND P.OBJ_TYPE=T.SID AND T.CODE='ACT.COORDINATION.AUTOPSY';

INSERT INTO T_OSI_AUTH_PRIV (OBJ_TYPE,ACTION) SELECT T.SID,A.SID FROM T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A WHERE T.CODE='ACT.COORDINATION.CC' AND A.CODE='CREATE';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV) SELECT R.SID,P.SID FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P,T_CORE_OBJ_TYPE T WHERE R.CODE='AGTPERS' AND P.OBJ_TYPE=T.SID AND T.CODE='ACT.COORDINATION.CC';

INSERT INTO T_OSI_AUTH_PRIV (OBJ_TYPE,ACTION) SELECT T.SID,A.SID FROM T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A WHERE T.CODE='ACT.COORDINATION.INV' AND A.CODE='CREATE';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV) SELECT R.SID,P.SID FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P,T_CORE_OBJ_TYPE T WHERE R.CODE='AGTPERS' AND P.OBJ_TYPE=T.SID AND T.CODE='ACT.COORDINATION.INV';
COMMIT;