UPDATE T_OSI_CHECKLIST_ITEM_TYPE_MAP SET COMPLETION_REQUIRED=0
WHERE STATUS_CHANGE_SID=(SELECT SID FROM T_OSI_STATUS_CHANGE WHERE CHECKLIST_BUTTON_LABEL='Initial Unit Review Checklist')
  AND CHECKLIST_ITEM_TYPE_SID=(SELECT SID FROM T_OSI_CHECKLIST_ITEM_TYPE WHERE TITLE='All Objectives Must be Met.');
COMMIT;   