set define off;

CREATE OR REPLACE PACKAGE BODY "OSI_MENU" AS
/******************************************************************************
   Name:     osi_menu
   Purpose:  Provides Functionality for OSI Menu Creation

   Revisions:
    Date        Author          Description
    ----------  --------------  ------------------------------------
    11-May-2012 Tim Ward        Created Package.
                                       
******************************************************************************/
    c_pipe   VARCHAR2(100) := Core_Util.get_config('CORE.PIPE_PREFIX') || 'OSI_MENU';

    PROCEDURE log_error(p_msg IN VARCHAR2) IS
    BEGIN
        Core_Logger.log_it(c_pipe, p_msg);
    END log_error;

    FUNCTION childrenCount(pMenuID in varchar2) return number is
            
            childCount number := 0;
    BEGIN
         select count(*) into childCount from t_osi_menu where parent_id=pMenuID and active='Y';

         return childCount;
    
    EXCEPTION WHEN OTHERS THEN
             
             return childCount;
                      
    END childrenCount;
    
    FUNCTION GetMenuHTML(pMenuID in varchar2, pTopLevelDescriptionReplace in varchar2 := NULL, pOtherNames in varchar2 := NULL, pOtherVals in varchar2 := NULL) return CLOB is
      
      SQLString     CLOB;
      topLevelClass varchar2(100) := ' class="sf-with-ul-top" ';
      topLevelli    varchar2(100) := ' class="sf-li-top" ';

    BEGIN
         SQLString := '<ul class="sf-menu">' || vCRLF;

         for m in (SELECT * from t_osi_menu where active='Y' START WITH id=pMenuId CONNECT BY prior id=parent_id order by seq)
         loop
             if(pOtherNames is not null and pOtherVals is not null) then
               
               if(m.command is null) then

                 SQLString := SQLString || '<li id="' || m.id || '"' || toplevelli || '><a' || toplevelclass || 'href="#">';
               
               else
                 
                 SQLString := SQLString || '<li id="' || m.id || '"' || toplevelli || '><a' || toplevelclass || 'href="' || replace(m.command,');',',' || '''' || pOtherNames || '''' || ',' || '''' || pOtherVals || '''' || ');') || '">';
               
               end if;

             else
  
               SQLString := SQLString || '<li id="' || m.id || '"' || toplevelli || '><a' || toplevelclass || 'href="' || nvl(m.command,'#') || '">';
               
             end if;
             
             if(m.icon is not null) then
  
               SQLString := SQLString || '<img class="sf-menu-img" " src="' || m.icon || '">';
  
             end if;
             
             if(m.id=pMenuId and pTopLevelDescriptionReplace is not null) then

               SQLString := SQLString || pTopLevelDescriptionReplace || '</a>';

             else

               SQLString := SQLString || m.description || '</a>';

             end if;
             
             if(childrenCount(m.id)>0) then

               SQLString := SQLString  || vCRLF || '<ul id="' || m.id || '_MAIN">' || vCRLF;
             
             else

               SQLString := SQLString || '</li>' || vCRLF;
             
             end if;
             if(m.last_child)='Y' then

               SQLString:=SQLString || '</ul>' || vCRLF;

             end if;             
             if(m.double_close)='Y' then

               SQLString:=SQLString || '</ul>' || vCRLF;

             end if;
             topLevelClass:=' ';
             topLevelli:=' ';
             
         end loop;
         SQLString := SQLString || '</ul>' || vCRLF;

         return SQLString;
         
    END GetMenuHTML;
    
END Osi_Menu;
/

