INSERT INTO T_CORE_TEMPLATE ( SID, TEMPLATE_NAME, TEMPLATE_INFO, MIME_TYPE, MIME_DISPOSITION, CREATE_BY, CREATE_ON, MODIFY_BY, MODIFY_ON ) VALUES ( '33315VDP', 'form686', NULL, NULL, 'ATTACHMENT', 'timothy.ward',  TO_Date( '01/20/2011 11:00:54 AM', 'MM/DD/YYYY HH:MI:SS AM'), 'timothy.ward',  TO_Date( '01/20/2011 11:01:10 AM', 'MM/DD/YYYY HH:MI:SS AM')); 
COMMIT;

INSERT INTO T_OSI_REPORT_TYPE (PICK_DISTS,PICK_CAVEATS,DESCRIPTION,OBJ_TYPE,PACKAGE_FUNCTION,MIME_TYPE) SELECT 'N','N','Form 686',T.SID,'OSI_REPORT.FORM686',M.SID FROM T_CORE_OBJ_TYPE T,T_OSI_REPORT_MIME_TYPE M WHERE CODE='ACT.DOCUMENT_REVIEW' AND UPPER(M.FILE_EXTENSION)='.RTF';
INSERT INTO T_OSI_REPORT_TYPE (PICK_DISTS,PICK_CAVEATS,DESCRIPTION,OBJ_TYPE,PACKAGE_FUNCTION,MIME_TYPE) SELECT 'N','N','Form 686',T.SID,'OSI_REPORT.FORM686',M.SID FROM T_CORE_OBJ_TYPE T,T_OSI_REPORT_MIME_TYPE M WHERE CODE='PART.INDIV' AND UPPER(M.FILE_EXTENSION)='.RTF';
COMMIT;