INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV) SELECT R.SID,P.SID FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P,T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A WHERE R.CODE IN ('BRANCH','COMMANDER','HQAPP','HQCOMMAND','HQPMO','HQPOLY','HQSOURCE','IMACC','IMASUPER','RGNCOMMAND','RGNIMA','RGNSC','RGNSOURCE','RGNSUPER','RGNVC','SOURCE','SQDCOMMAND','SUPER') AND T.CODE='FILE.SOURCE' AND T.SID=P.OBJ_TYPE AND A.CODE='XFR' AND A.SID=P.ACTION;
commit;

/*
SELECT R.SID FROM T_OSI_AUTH_ROLE R WHERE R.CODE IN ('BRANCH','COMMANDER','HQAPP','HQCOMMAND','HQPMO','HQPOLY','HQSOURCE','IMACC','IMASUPER','RGNCOMMAND','RGNIMA','RGNSC','RGNSOURCE','RGNSUPER','RGNVC','SOURCE','SQDCOMMAND','SUPER')

SELECT P.SID FROM T_OSI_AUTH_PRIV P,T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A WHERE  T.CODE='FILE.SOURCE' AND T.SID=P.OBJ_TYPE AND A.CODE='XFR' AND A.SID=P.ACTION;
*/