INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV) SELECT R.SID,P.SID FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P,T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A WHERE R.CODE IN ('BRANCH','COMMANDER','HQCOMMAND','HQPMO','IMACC','IMASUPER','RGNCOMMAND','RGNIMA','RGNSUPER','RGNVC','SQDCOMMAND','SUPER') AND T.CODE='FILE.INV.CASE' AND T.SID=P.OBJ_TYPE AND A.CODE='CLOSE_SHRT' AND A.SID=P.ACTION;
COMMIT;
