INSERT INTO T_OSI_REPORT_TYPE (OBJ_TYPE,DESCRIPTION,PICK_CAVEATS,PICK_DISTS,PACKAGE_FUNCTION,MIME_TYPE) 
      SELECT O.SID,'File Barcode Label','N','N','OSI_FILE.RPT_GENERATE_30252',M.SID FROM T_CORE_OBJ_TYPE O,T_OSI_REPORT_MIME_TYPE M WHERE O.CODE='FILE.AAPP' AND UPPER(MIME_TYPE)='APPLICATION/RTF';

INSERT INTO T_OSI_REPORT_TYPE (OBJ_TYPE,DESCRIPTION,PICK_CAVEATS,PICK_DISTS,PACKAGE_FUNCTION,MIME_TYPE) 
      SELECT O.SID,'Form 2','N','N','OSI_FILE.RPT_GENERATE_FORM2',M.SID FROM T_CORE_OBJ_TYPE O,T_OSI_REPORT_MIME_TYPE M WHERE O.CODE='FILE.AAPP' AND UPPER(MIME_TYPE)='APPLICATION/RTF';

INSERT INTO T_OSI_REPORT_TYPE (OBJ_TYPE,DESCRIPTION,PICK_CAVEATS,PICK_DISTS,PACKAGE_FUNCTION,MIME_TYPE) 
      SELECT O.SID,'Form 3986 Label','N','N','OSI_FILE.RPT_GENERATE_30256',M.SID FROM T_CORE_OBJ_TYPE O,T_OSI_REPORT_MIME_TYPE M WHERE O.CODE='FILE.AAPP' AND UPPER(MIME_TYPE)='APPLICATION/RTF';

COMMIT;