SET DEFINE OFF;
Insert into T_OSI_NOTE_TYPE
   (SID, OBJ_TYPE, USAGE, CODE, DESCRIPTION, LOCK_MODE, SEQ, ACTIVE, OVERRIDE)
 Values
   ('2220S242', '22200000AJG', 'NOTELIST', 'CLOSURE', 'Close Case Note', 'IMMED', 1, 'N', 'N');
COMMIT;
