-------------------------------------------------------------------
--- Give the SFS Investigations Privileges to the Correct Roles ---
-------------------------------------------------------------------

---ACCESS---
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y' FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='HQPMO' AND P.DESCRIPTION='SFS: Access an SFS Investigative file';

INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y' FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='AGTPERS' AND P.DESCRIPTION='SFS: Access an SFS Investigative file';

---APPROVE---
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='BRANCH' AND P.DESCRIPTION='SFS: Approve an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='COMMANDER' AND P.DESCRIPTION='SFS: Approve an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='HQPMO' AND P.DESCRIPTION='SFS: Approve an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='IMACC' AND P.DESCRIPTION='SFS: Approve an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'N'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='IMASUPER' AND P.DESCRIPTION='SFS: Approve an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='RGNCOMMAND' AND P.DESCRIPTION='SFS: Approve an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='RGNIMA' AND P.DESCRIPTION='SFS: Approve an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='RGNSUPER' AND P.DESCRIPTION='SFS: Approve an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='RGNVC' AND P.DESCRIPTION='SFS: Approve an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='SQDCOMMAND' AND P.DESCRIPTION='SFS: Approve an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'N'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='SUPER' AND P.DESCRIPTION='SFS: Approve an SFS Investigative file';

---CLOSE---
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='BRANCH' AND P.DESCRIPTION='SFS: Close an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='COMMANDER' AND P.DESCRIPTION='SFS: Close an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='HQPMO' AND P.DESCRIPTION='SFS: Close an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='IMACC' AND P.DESCRIPTION='SFS: Close an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'N'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='IMASUPER' AND P.DESCRIPTION='SFS: Close an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='RGNCOMMAND' AND P.DESCRIPTION='SFS: Close an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='RGNIMA' AND P.DESCRIPTION='SFS: Close an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='RGNSUPER' AND P.DESCRIPTION='SFS: Close an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='RGNVC' AND P.DESCRIPTION='SFS: Close an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='SQDCOMMAND' AND P.DESCRIPTION='SFS: Close an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'N'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='SUPER' AND P.DESCRIPTION='SFS: Close an SFS Investigative file';

---CREATE---
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='AGTPERS' AND P.DESCRIPTION='SFS: Create an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'N'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='FRNNATL' AND P.DESCRIPTION='SFS: Create an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='HQPMO' AND P.DESCRIPTION='SFS: Create an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='SUPPORT' AND P.DESCRIPTION='SFS: Create an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'N'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='UFRNNATL' AND P.DESCRIPTION='SFS: Create an SFS Investigative file';

---DELETE---
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='BRANCH' AND P.DESCRIPTION='SFS: Delete an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='COMMANDER' AND P.DESCRIPTION='SFS: Delete an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='HQPMO' AND P.DESCRIPTION='SFS: Delete an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='IMACC' AND P.DESCRIPTION='SFS: Delete an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'N'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='IMASUPER' AND P.DESCRIPTION='SFS: Delete an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='RGNCOMMAND' AND P.DESCRIPTION='SFS: Delete an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='RGNIMA' AND P.DESCRIPTION='SFS: Delete an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='RGNSUPER' AND P.DESCRIPTION='SFS: Delete an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='RGNVC' AND P.DESCRIPTION='SFS: Delete an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='SQDCOMMAND' AND P.DESCRIPTION='SFS: Delete an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'N'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='SUPER' AND P.DESCRIPTION='SFS: Delete an SFS Investigative file';

---GENERATE REPORTS---
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='AGTPERS' AND P.DESCRIPTION='SFS: Generate reports';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='HQPMO' AND P.DESCRIPTION='SFS: Generate reports';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='SUPPORT' AND P.DESCRIPTION='SFS: Generate reports';

---UPDATE NO UNIT CHECK---
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='AGTPERS' AND P.DESCRIPTION='SFS: Update an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='HQPMO' AND P.DESCRIPTION='SFS: Update an SFS Investigative file';
COMMIT;

----------------------------
---UPDATE UNIT CHECK PRIV---
INSERT INTO T_OSI_AUTH_PRIV (OBJ_TYPE,ACTION,DESCRIPTION)
SELECT T.SID,A.SID,'SFS: Update w/Unit Check an SFS Investigative file' FROM T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A WHERE T.CODE='FILE.SFS' AND A.CODE='UPDATE_UNT';
COMMIT;

---ADD UPDATE UNIT CHECK PRIV TO ROLE(S)---
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='FRNNATL' AND P.DESCRIPTION='SFS: Update w/Unit Check an SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='UFRNNATL' AND P.DESCRIPTION='SFS: Update w/Unit Check an SFS Investigative file';
COMMIT;


-------------------------------------------------
-------------------------------------------------
-------------------------------------------------
INSERT INTO T_OSI_AUTH_PRIV (OBJ_TYPE,ACTION,DESCRIPTION)
SELECT T.SID,A.SID,'SFS: Access Unit SFS Investigative file' FROM T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A WHERE T.CODE='FILE.SFS' AND A.CODE='ACCESS_UNT';

INSERT INTO T_OSI_AUTH_PRIV (OBJ_TYPE,ACTION,DESCRIPTION)
SELECT T.SID,A.SID,'SFS: Access Assigned SFS Investigative file' FROM T_CORE_OBJ_TYPE T,T_OSI_AUTH_ACTION_TYPE A WHERE T.CODE='FILE.SFS' AND A.CODE='ACCESS_ASS';
COMMIT;

---ACCESS ASSGINED ONLY---
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='FRNNATL' AND P.DESCRIPTION='SFS: Access Assigned SFS Investigative file';
COMMIT;

---ACCESS UNIT AND ASSGINED ---
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='UFRNNATL' AND P.DESCRIPTION='SFS: Access Unit SFS Investigative file';
INSERT INTO T_OSI_AUTH_ROLE_PRIV (ROLE,PRIV,GRANTABLE)
SELECT R.SID,P.SID,'Y'  FROM T_OSI_AUTH_ROLE R,T_OSI_AUTH_PRIV P WHERE CODE='UFRNNATL' AND P.DESCRIPTION='SFS: Access Assigned SFS Investigative file';
COMMIT
